# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/example-php
codecov:
  token: 6af8e8be-ce7f-4971-ba0f-687f025360ef
  secret: vpQA/BWXzzv4jwKWnc7yqvXiPD6/96bJHwSCeq2jpwCTp/AkCu5zTZAGVeOH8/85w6AXTo8FmvdVpkm2T28mQQ==
coverage:
  range: 95..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        base: auto
    patch: off
comment: false
